#!/bin/bash

clean=0

build_win32() {
  mkdir -p build_win32; pushd build_win32
  rm data resource
  ln -s ../data ../resource .

  i686-w64-mingw32-windres resource/win32_res.rc win32_res.o

  ../configure --enable-pch --target=i686-w64-mingw32 --with-wx-config=/usr/i686-w64-mingw32/lib/wx/config/i686-w64-mingw32-msw-unicode-release-static-2.8 \
    --with-boost=/usr/i686-w64-mingw32/  CXX="i686-w64-mingw32-g++" LDFLAGS="-static" LDADD="-lgdiplus -llzma win32_res.o"
  if [ $clean = 1 ]; then
    make clean
  fi
  make -j4
  i686-w64-mingw32-g++ -static -o magicseteditor.com ../src/cli/win32_cli_wrapper.cpp win32_res.o

  popd
}
build_linux() {
  mkdir -p build_linux; pushd build_linux

  ../configure --with-wx-config=wx-config-2.8
  if [ $clean = 1 ]; then
    make clean
  fi
  make -j4

  popd
}
build_dist() {
  echo ""
}

case $1 in
  win32)
    build_win32
    ;;
  linux)
    build_linux
    ;;
  dist)
    clean=1
    build_win32
    build_linux
    build_dist
    ;;
esac
