# Makefile.in generated by automake 1.9.6 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005  Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



#+----------------------------------------------------------------------------+
#| Description:  Magic Set Editor - Program to make Magic (tm) cards          |
#| Copyright:    (C) 2001 - 2007 Twan van Laarhoven                           |
#| License:      GNU General Public License 2 or later (see file COPYING)     |
#+----------------------------------------------------------------------------+

srcdir = .
top_srcdir = .

pkgdatadir = $(datadir)/magicseteditor
pkglibdir = $(libdir)/magicseteditor
pkgincludedir = $(includedir)/magicseteditor
top_builddir = .
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
INSTALL = /usr/bin/install -c
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = magicseteditor$(EXEEXT)
subdir = .
DIST_COMMON = $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(top_srcdir)/configure \
	$(top_srcdir)/src/config.h.in COPYING TODO depcomp install-sh \
	missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno configure.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/src/config.h
CONFIG_CLEAN_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
binPROGRAMS_INSTALL = $(INSTALL_PROGRAM)
PROGRAMS = $(bin_PROGRAMS)
am__dirstamp = $(am__leading_dot)dirstamp
am_magicseteditor_OBJECTS = ./src/gfx/color.$(OBJEXT) \
	./src/gfx/bezier.$(OBJEXT) ./src/gfx/blend_image.$(OBJEXT) \
	./src/gfx/resample_image.$(OBJEXT) \
	./src/gfx/resample_text.$(OBJEXT) \
	./src/gfx/image_effects.$(OBJEXT) \
	./src/gfx/rotate_image.$(OBJEXT) \
	./src/gfx/combine_image.$(OBJEXT) \
	./src/gfx/polynomial.$(OBJEXT) ./src/gfx/mask_image.$(OBJEXT) \
	./src/gui/set/stats_panel.$(OBJEXT) \
	./src/gui/set/panel.$(OBJEXT) \
	./src/gui/set/set_info_panel.$(OBJEXT) \
	./src/gui/set/style_panel.$(OBJEXT) \
	./src/gui/set/keywords_panel.$(OBJEXT) \
	./src/gui/set/window.$(OBJEXT) \
	./src/gui/set/cards_panel.$(OBJEXT) \
	./src/gui/control/card_viewer.$(OBJEXT) \
	./src/gui/control/filtered_card_list.$(OBJEXT) \
	./src/gui/control/select_card_list.$(OBJEXT) \
	./src/gui/control/package_list.$(OBJEXT) \
	./src/gui/control/gallery_list.$(OBJEXT) \
	./src/gui/control/graph.$(OBJEXT) \
	./src/gui/control/image_card_list.$(OBJEXT) \
	./src/gui/control/card_list.$(OBJEXT) \
	./src/gui/control/card_list_column_select.$(OBJEXT) \
	./src/gui/control/native_look_editor.$(OBJEXT) \
	./src/gui/control/card_editor.$(OBJEXT) \
	./src/gui/control/text_ctrl.$(OBJEXT) \
	./src/gui/preferences_window.$(OBJEXT) \
	./src/gui/drop_down_list.$(OBJEXT) \
	./src/gui/card_select_window.$(OBJEXT) \
	./src/gui/welcome_window.$(OBJEXT) \
	./src/gui/value/color.$(OBJEXT) \
	./src/gui/value/symbol.$(OBJEXT) \
	./src/gui/value/multiple_choice.$(OBJEXT) \
	./src/gui/value/choice.$(OBJEXT) \
	./src/gui/value/text.$(OBJEXT) ./src/gui/value/image.$(OBJEXT) \
	./src/gui/value/editor.$(OBJEXT) \
	./src/gui/image_slice_window.$(OBJEXT) \
	./src/gui/thumbnail_thread.$(OBJEXT) \
	./src/gui/print_window.$(OBJEXT) \
	./src/gui/about_window.$(OBJEXT) \
	./src/gui/symbol/point_editor.$(OBJEXT) \
	./src/gui/symbol/basic_shape_editor.$(OBJEXT) \
	./src/gui/symbol/control.$(OBJEXT) \
	./src/gui/symbol/select_editor.$(OBJEXT) \
	./src/gui/symbol/editor.$(OBJEXT) \
	./src/gui/symbol/part_list.$(OBJEXT) \
	./src/gui/symbol/window.$(OBJEXT) \
	./src/gui/update_checker.$(OBJEXT) \
	./src/gui/new_window.$(OBJEXT) ./src/gui/icon_menu.$(OBJEXT) \
	./src/gui/util.$(OBJEXT) ./src/data/field.$(OBJEXT) \
	./src/data/field/color.$(OBJEXT) \
	./src/data/field/symbol.$(OBJEXT) \
	./src/data/field/multiple_choice.$(OBJEXT) \
	./src/data/field/choice.$(OBJEXT) \
	./src/data/field/boolean.$(OBJEXT) \
	./src/data/field/text.$(OBJEXT) \
	./src/data/field/image.$(OBJEXT) ./src/data/symbol.$(OBJEXT) \
	./src/data/stylesheet.$(OBJEXT) ./src/data/set.$(OBJEXT) \
	./src/data/font.$(OBJEXT) ./src/data/locale.$(OBJEXT) \
	./src/data/symbol_font.$(OBJEXT) \
	./src/data/action/symbol.$(OBJEXT) \
	./src/data/action/set.$(OBJEXT) \
	./src/data/action/symbol_part.$(OBJEXT) \
	./src/data/action/value.$(OBJEXT) ./src/data/card.$(OBJEXT) \
	./src/data/format/html.$(OBJEXT) \
	./src/data/format/apprentice.$(OBJEXT) \
	./src/data/format/mtg_editor.$(OBJEXT) \
	./src/data/format/formats.$(OBJEXT) \
	./src/data/format/image.$(OBJEXT) \
	./src/data/format/mws.$(OBJEXT) \
	./src/data/format/mse1.$(OBJEXT) \
	./src/data/format/mse2.$(OBJEXT) \
	./src/data/format/clipboard.$(OBJEXT) \
	./src/data/statistics.$(OBJEXT) ./src/data/settings.$(OBJEXT) \
	./src/data/keyword.$(OBJEXT) ./src/data/game.$(OBJEXT) \
	./src/util/io/package.$(OBJEXT) ./src/util/io/writer.$(OBJEXT) \
	./src/util/io/get_member.$(OBJEXT) \
	./src/util/io/reader.$(OBJEXT) \
	./src/util/io/package_manager.$(OBJEXT) \
	./src/util/rotation.$(OBJEXT) \
	./src/util/action_stack.$(OBJEXT) \
	./src/util/alignment.$(OBJEXT) ./src/util/version.$(OBJEXT) \
	./src/util/string.$(OBJEXT) ./src/util/tagged_string.$(OBJEXT) \
	./src/util/age.$(OBJEXT) ./src/util/error.$(OBJEXT) \
	./src/main.$(OBJEXT) ./src/code_template.$(OBJEXT) \
	./src/render/card/viewer.$(OBJEXT) \
	./src/render/text/symbol.$(OBJEXT) \
	./src/render/text/font.$(OBJEXT) \
	./src/render/text/compound.$(OBJEXT) \
	./src/render/text/viewer.$(OBJEXT) \
	./src/render/text/element.$(OBJEXT) \
	./src/render/value/color.$(OBJEXT) \
	./src/render/value/symbol.$(OBJEXT) \
	./src/render/value/multiple_choice.$(OBJEXT) \
	./src/render/value/choice.$(OBJEXT) \
	./src/render/value/text.$(OBJEXT) \
	./src/render/value/image.$(OBJEXT) \
	./src/render/value/viewer.$(OBJEXT) \
	./src/render/symbol/filter.$(OBJEXT) \
	./src/render/symbol/viewer.$(OBJEXT) \
	./src/script/parser.$(OBJEXT) ./src/script/functions.$(OBJEXT) \
	./src/script/image.$(OBJEXT) ./src/script/dependency.$(OBJEXT) \
	./src/script/value.$(OBJEXT) ./src/script/script.$(OBJEXT) \
	./src/script/context.$(OBJEXT) \
	./src/script/script_manager.$(OBJEXT) \
	./src/script/scriptable.$(OBJEXT)
magicseteditor_OBJECTS = $(am_magicseteditor_OBJECTS)
magicseteditor_LDADD = $(LDADD)
DEFAULT_INCLUDES = -I. -I$(srcdir) -I$(top_builddir)/src
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
SOURCES = $(magicseteditor_SOURCES)
DIST_SOURCES = $(magicseteditor_SOURCES)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d $(distdir) \
    || { find $(distdir) -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr $(distdir); }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/coppro/C++/MSE/trunk/missing --run aclocal-1.9
AMDEP_FALSE = #
AMDEP_TRUE = 
AMTAR = ${SHELL} /home/coppro/C++/MSE/trunk/missing --run tar
AUTOCONF = ${SHELL} /home/coppro/C++/MSE/trunk/missing --run autoconf
AUTOHEADER = ${SHELL} /home/coppro/C++/MSE/trunk/missing --run autoheader
AUTOMAKE = ${SHELL} /home/coppro/C++/MSE/trunk/missing --run automake-1.9
AWK = mawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
GREP = /bin/grep
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/coppro/C++/MSE/trunk/missing --run makeinfo
OBJEXT = o
PACKAGE = magicseteditor
PACKAGE_BUGREPORT = twanvl@users.sourceforge.net
PACKAGE_NAME = magicseteditor
PACKAGE_STRING = magicseteditor 0.3.0
PACKAGE_TARNAME = magicseteditor
PACKAGE_VERSION = 0.3.0
PATH_SEPARATOR = :
SET_MAKE = 
SHELL = /bin/bash
STRIP = 
VERSION = 0.3.0
WX_CFLAGS = -I/usr/lib/wx/include/gtk2-unicode-release-2.6 -I/usr/include/wx-2.6 -DGTK_NO_CHECK_CASTS -D__WXGTK__ -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -DNO_GCC_PRAGMA 
WX_CFLAGS_ONLY = 
WX_CONFIG_PATH = /usr/bin/wx-config
WX_CPPFLAGS = -I/usr/lib/wx/include/gtk2-unicode-release-2.6 -I/usr/include/wx-2.6 -DGTK_NO_CHECK_CASTS -D__WXGTK__ -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -DNO_GCC_PRAGMA
WX_CXXFLAGS = -I/usr/lib/wx/include/gtk2-unicode-release-2.6 -I/usr/include/wx-2.6 -DGTK_NO_CHECK_CASTS -D__WXGTK__ -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -DNO_GCC_PRAGMA  
WX_CXXFLAGS_ONLY = -I/usr/lib/wx/include/gtk2-unicode-release-2.6 -I/usr/include/wx-2.6 -DGTK_NO_CHECK_CASTS -D__WXGTK__ -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -DNO_GCC_PRAGMA
WX_LIBS = -pthread   -lwx_gtk2u_xrc-2.6 -lwx_gtk2u_qa-2.6 -lwx_gtk2u_html-2.6 -lwx_gtk2u_adv-2.6 -lwx_gtk2u_core-2.6 -lwx_baseu_xml-2.6 -lwx_baseu_net-2.6 -lwx_baseu-2.6 
WX_LIBS_STATIC =  -pthread    /usr/lib/libwx_gtk-2.4.a -L/usr/lib -lgtk -lgdk -rdynamic -lgmodule -lgthread -lglib -lpthread -ldl -lXi -lXext -lX11 -lm -lpng -ljpeg -ltiff -lz -ldl -lm 
WX_VERSION = 2.6.3
ac_ct_CC = gcc
ac_ct_CXX = g++
am__fastdepCC_FALSE = #
am__fastdepCC_TRUE = 
am__fastdepCXX_FALSE = #
am__fastdepCXX_TRUE = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build_alias = 
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = /home/coppro/C++/MSE/trunk/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = mkdir -p --
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
sysconfdir = ${prefix}/etc
target_alias = 

# This flag allows us to use subdirectories:
AUTOMAKE_OPTIONS = subdir-objects
AM_CXXFLAGS = -I/usr/lib/wx/include/gtk2-unicode-release-2.6 -I/usr/include/wx-2.6 -DGTK_NO_CHECK_CASTS -D__WXGTK__ -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -DNO_GCC_PRAGMA   -DUNICODE -I . -Wall
AM_LDFLAGS = -pthread   -lwx_gtk2u_xrc-2.6 -lwx_gtk2u_qa-2.6 -lwx_gtk2u_html-2.6 -lwx_gtk2u_adv-2.6 -lwx_gtk2u_core-2.6 -lwx_baseu_xml-2.6 -lwx_baseu_net-2.6 -lwx_baseu-2.6 

# List of source files, generated using:
# find . -name *.cpp | sed "s/\./magicseteditor_SOURCES += ./"
magicseteditor_SOURCES = ./src/gfx/color.cpp ./src/gfx/bezier.cpp \
	./src/gfx/blend_image.cpp ./src/gfx/resample_image.cpp \
	./src/gfx/resample_text.cpp ./src/gfx/image_effects.cpp \
	./src/gfx/rotate_image.cpp ./src/gfx/combine_image.cpp \
	./src/gfx/polynomial.cpp ./src/gfx/mask_image.cpp \
	./src/gui/set/stats_panel.cpp ./src/gui/set/panel.cpp \
	./src/gui/set/set_info_panel.cpp ./src/gui/set/style_panel.cpp \
	./src/gui/set/keywords_panel.cpp ./src/gui/set/window.cpp \
	./src/gui/set/cards_panel.cpp \
	./src/gui/control/card_viewer.cpp \
	./src/gui/control/filtered_card_list.cpp \
	./src/gui/control/select_card_list.cpp \
	./src/gui/control/package_list.cpp \
	./src/gui/control/gallery_list.cpp ./src/gui/control/graph.cpp \
	./src/gui/control/image_card_list.cpp \
	./src/gui/control/card_list.cpp \
	./src/gui/control/card_list_column_select.cpp \
	./src/gui/control/native_look_editor.cpp \
	./src/gui/control/card_editor.cpp \
	./src/gui/control/text_ctrl.cpp \
	./src/gui/preferences_window.cpp ./src/gui/drop_down_list.cpp \
	./src/gui/card_select_window.cpp ./src/gui/welcome_window.cpp \
	./src/gui/value/color.cpp ./src/gui/value/symbol.cpp \
	./src/gui/value/multiple_choice.cpp ./src/gui/value/choice.cpp \
	./src/gui/value/text.cpp ./src/gui/value/image.cpp \
	./src/gui/value/editor.cpp ./src/gui/image_slice_window.cpp \
	./src/gui/thumbnail_thread.cpp ./src/gui/print_window.cpp \
	./src/gui/about_window.cpp ./src/gui/symbol/point_editor.cpp \
	./src/gui/symbol/basic_shape_editor.cpp \
	./src/gui/symbol/control.cpp \
	./src/gui/symbol/select_editor.cpp ./src/gui/symbol/editor.cpp \
	./src/gui/symbol/part_list.cpp ./src/gui/symbol/window.cpp \
	./src/gui/update_checker.cpp ./src/gui/new_window.cpp \
	./src/gui/icon_menu.cpp ./src/gui/util.cpp \
	./src/data/field.cpp ./src/data/field/color.cpp \
	./src/data/field/symbol.cpp \
	./src/data/field/multiple_choice.cpp \
	./src/data/field/choice.cpp ./src/data/field/boolean.cpp \
	./src/data/field/text.cpp ./src/data/field/image.cpp \
	./src/data/symbol.cpp ./src/data/stylesheet.cpp \
	./src/data/set.cpp ./src/data/font.cpp ./src/data/locale.cpp \
	./src/data/symbol_font.cpp ./src/data/action/symbol.cpp \
	./src/data/action/set.cpp ./src/data/action/symbol_part.cpp \
	./src/data/action/value.cpp ./src/data/card.cpp \
	./src/data/format/html.cpp ./src/data/format/apprentice.cpp \
	./src/data/format/mtg_editor.cpp ./src/data/format/formats.cpp \
	./src/data/format/image.cpp ./src/data/format/mws.cpp \
	./src/data/format/mse1.cpp ./src/data/format/mse2.cpp \
	./src/data/format/clipboard.cpp ./src/data/statistics.cpp \
	./src/data/settings.cpp ./src/data/keyword.cpp \
	./src/data/game.cpp ./src/util/io/package.cpp \
	./src/util/io/writer.cpp ./src/util/io/get_member.cpp \
	./src/util/io/reader.cpp ./src/util/io/package_manager.cpp \
	./src/util/rotation.cpp ./src/util/action_stack.cpp \
	./src/util/alignment.cpp ./src/util/version.cpp \
	./src/util/string.cpp ./src/util/tagged_string.cpp \
	./src/util/age.cpp ./src/util/error.cpp ./src/main.cpp \
	./src/code_template.cpp ./src/render/card/viewer.cpp \
	./src/render/text/symbol.cpp ./src/render/text/font.cpp \
	./src/render/text/compound.cpp ./src/render/text/viewer.cpp \
	./src/render/text/element.cpp ./src/render/value/color.cpp \
	./src/render/value/symbol.cpp \
	./src/render/value/multiple_choice.cpp \
	./src/render/value/choice.cpp ./src/render/value/text.cpp \
	./src/render/value/image.cpp ./src/render/value/viewer.cpp \
	./src/render/symbol/filter.cpp ./src/render/symbol/viewer.cpp \
	./src/script/parser.cpp ./src/script/functions.cpp \
	./src/script/image.cpp ./src/script/dependency.cpp \
	./src/script/value.cpp ./src/script/script.cpp \
	./src/script/context.cpp ./src/script/script_manager.cpp \
	./src/script/scriptable.cpp
all: all-am

.SUFFIXES:
.SUFFIXES: .cpp .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign '; \
	      cd $(srcdir) && $(AUTOMAKE) --foreign  \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign  Makefile'; \
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --foreign  Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)

src/config.h: src/stamp-h1
	@if test ! -f $@; then \
	  rm -f src/stamp-h1; \
	  $(MAKE) src/stamp-h1; \
	else :; fi

src/stamp-h1: $(top_srcdir)/src/config.h.in $(top_builddir)/config.status
	@rm -f src/stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status src/config.h
$(top_srcdir)/src/config.h.in:  $(am__configure_deps) 
	cd $(top_srcdir) && $(AUTOHEADER)
	rm -f src/stamp-h1
	touch $@

distclean-hdr:
	-rm -f src/config.h src/stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(mkdir_p) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  if test -f $$p \
	  ; then \
	    f=`echo "$$p1" | sed 's,^.*/,,;$(transform);s/$$/$(EXEEXT)/'`; \
	   echo " $(INSTALL_PROGRAM_ENV) $(binPROGRAMS_INSTALL) '$$p' '$(DESTDIR)$(bindir)/$$f'"; \
	   $(INSTALL_PROGRAM_ENV) $(binPROGRAMS_INSTALL) "$$p" "$(DESTDIR)$(bindir)/$$f" || exit 1; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo "$$p" | sed 's,^.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  echo " rm -f '$(DESTDIR)$(bindir)/$$f'"; \
	  rm -f "$(DESTDIR)$(bindir)/$$f"; \
	done

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
src/gfx/$(am__dirstamp):
	@$(mkdir_p) ./src/gfx
	@: > src/gfx/$(am__dirstamp)
src/gfx/$(DEPDIR)/$(am__dirstamp):
	@$(mkdir_p) ./src/gfx/$(DEPDIR)
	@: > src/gfx/$(DEPDIR)/$(am__dirstamp)
./src/gfx/color.$(OBJEXT): src/gfx/$(am__dirstamp) \
	src/gfx/$(DEPDIR)/$(am__dirstamp)
./src/gfx/bezier.$(OBJEXT): src/gfx/$(am__dirstamp) \
	src/gfx/$(DEPDIR)/$(am__dirstamp)
./src/gfx/blend_image.$(OBJEXT): src/gfx/$(am__dirstamp) \
	src/gfx/$(DEPDIR)/$(am__dirstamp)
./src/gfx/resample_image.$(OBJEXT): src/gfx/$(am__dirstamp) \
	src/gfx/$(DEPDIR)/$(am__dirstamp)
./src/gfx/resample_text.$(OBJEXT): src/gfx/$(am__dirstamp) \
	src/gfx/$(DEPDIR)/$(am__dirstamp)
./src/gfx/image_effects.$(OBJEXT): src/gfx/$(am__dirstamp) \
	src/gfx/$(DEPDIR)/$(am__dirstamp)
./src/gfx/rotate_image.$(OBJEXT): src/gfx/$(am__dirstamp) \
	src/gfx/$(DEPDIR)/$(am__dirstamp)
./src/gfx/combine_image.$(OBJEXT): src/gfx/$(am__dirstamp) \
	src/gfx/$(DEPDIR)/$(am__dirstamp)
./src/gfx/polynomial.$(OBJEXT): src/gfx/$(am__dirstamp) \
	src/gfx/$(DEPDIR)/$(am__dirstamp)
./src/gfx/mask_image.$(OBJEXT): src/gfx/$(am__dirstamp) \
	src/gfx/$(DEPDIR)/$(am__dirstamp)
src/gui/set/$(am__dirstamp):
	@$(mkdir_p) ./src/gui/set
	@: > src/gui/set/$(am__dirstamp)
src/gui/set/$(DEPDIR)/$(am__dirstamp):
	@$(mkdir_p) ./src/gui/set/$(DEPDIR)
	@: > src/gui/set/$(DEPDIR)/$(am__dirstamp)
./src/gui/set/stats_panel.$(OBJEXT): src/gui/set/$(am__dirstamp) \
	src/gui/set/$(DEPDIR)/$(am__dirstamp)
./src/gui/set/panel.$(OBJEXT): src/gui/set/$(am__dirstamp) \
	src/gui/set/$(DEPDIR)/$(am__dirstamp)
./src/gui/set/set_info_panel.$(OBJEXT): src/gui/set/$(am__dirstamp) \
	src/gui/set/$(DEPDIR)/$(am__dirstamp)
./src/gui/set/style_panel.$(OBJEXT): src/gui/set/$(am__dirstamp) \
	src/gui/set/$(DEPDIR)/$(am__dirstamp)
./src/gui/set/keywords_panel.$(OBJEXT): src/gui/set/$(am__dirstamp) \
	src/gui/set/$(DEPDIR)/$(am__dirstamp)
./src/gui/set/window.$(OBJEXT): src/gui/set/$(am__dirstamp) \
	src/gui/set/$(DEPDIR)/$(am__dirstamp)
./src/gui/set/cards_panel.$(OBJEXT): src/gui/set/$(am__dirstamp) \
	src/gui/set/$(DEPDIR)/$(am__dirstamp)
src/gui/control/$(am__dirstamp):
	@$(mkdir_p) ./src/gui/control
	@: > src/gui/control/$(am__dirstamp)
src/gui/control/$(DEPDIR)/$(am__dirstamp):
	@$(mkdir_p) ./src/gui/control/$(DEPDIR)
	@: > src/gui/control/$(DEPDIR)/$(am__dirstamp)
./src/gui/control/card_viewer.$(OBJEXT):  \
	src/gui/control/$(am__dirstamp) \
	src/gui/control/$(DEPDIR)/$(am__dirstamp)
./src/gui/control/filtered_card_list.$(OBJEXT):  \
	src/gui/control/$(am__dirstamp) \
	src/gui/control/$(DEPDIR)/$(am__dirstamp)
./src/gui/control/select_card_list.$(OBJEXT):  \
	src/gui/control/$(am__dirstamp) \
	src/gui/control/$(DEPDIR)/$(am__dirstamp)
./src/gui/control/package_list.$(OBJEXT):  \
	src/gui/control/$(am__dirstamp) \
	src/gui/control/$(DEPDIR)/$(am__dirstamp)
./src/gui/control/gallery_list.$(OBJEXT):  \
	src/gui/control/$(am__dirstamp) \
	src/gui/control/$(DEPDIR)/$(am__dirstamp)
./src/gui/control/graph.$(OBJEXT): src/gui/control/$(am__dirstamp) \
	src/gui/control/$(DEPDIR)/$(am__dirstamp)
./src/gui/control/image_card_list.$(OBJEXT):  \
	src/gui/control/$(am__dirstamp) \
	src/gui/control/$(DEPDIR)/$(am__dirstamp)
./src/gui/control/card_list.$(OBJEXT):  \
	src/gui/control/$(am__dirstamp) \
	src/gui/control/$(DEPDIR)/$(am__dirstamp)
./src/gui/control/card_list_column_select.$(OBJEXT):  \
	src/gui/control/$(am__dirstamp) \
	src/gui/control/$(DEPDIR)/$(am__dirstamp)
./src/gui/control/native_look_editor.$(OBJEXT):  \
	src/gui/control/$(am__dirstamp) \
	src/gui/control/$(DEPDIR)/$(am__dirstamp)
./src/gui/control/card_editor.$(OBJEXT):  \
	src/gui/control/$(am__dirstamp) \
	src/gui/control/$(DEPDIR)/$(am__dirstamp)
./src/gui/control/text_ctrl.$(OBJEXT):  \
	src/gui/control/$(am__dirstamp) \
	src/gui/control/$(DEPDIR)/$(am__dirstamp)
src/gui/$(am__dirstamp):
	@$(mkdir_p) ./src/gui
	@: > src/gui/$(am__dirstamp)
src/gui/$(DEPDIR)/$(am__dirstamp):
	@$(mkdir_p) ./src/gui/$(DEPDIR)
	@: > src/gui/$(DEPDIR)/$(am__dirstamp)
./src/gui/preferences_window.$(OBJEXT): src/gui/$(am__dirstamp) \
	src/gui/$(DEPDIR)/$(am__dirstamp)
./src/gui/drop_down_list.$(OBJEXT): src/gui/$(am__dirstamp) \
	src/gui/$(DEPDIR)/$(am__dirstamp)
./src/gui/card_select_window.$(OBJEXT): src/gui/$(am__dirstamp) \
	src/gui/$(DEPDIR)/$(am__dirstamp)
./src/gui/welcome_window.$(OBJEXT): src/gui/$(am__dirstamp) \
	src/gui/$(DEPDIR)/$(am__dirstamp)
src/gui/value/$(am__dirstamp):
	@$(mkdir_p) ./src/gui/value
	@: > src/gui/value/$(am__dirstamp)
src/gui/value/$(DEPDIR)/$(am__dirstamp):
	@$(mkdir_p) ./src/gui/value/$(DEPDIR)
	@: > src/gui/value/$(DEPDIR)/$(am__dirstamp)
./src/gui/value/color.$(OBJEXT): src/gui/value/$(am__dirstamp) \
	src/gui/value/$(DEPDIR)/$(am__dirstamp)
./src/gui/value/symbol.$(OBJEXT): src/gui/value/$(am__dirstamp) \
	src/gui/value/$(DEPDIR)/$(am__dirstamp)
./src/gui/value/multiple_choice.$(OBJEXT):  \
	src/gui/value/$(am__dirstamp) \
	src/gui/value/$(DEPDIR)/$(am__dirstamp)
./src/gui/value/choice.$(OBJEXT): src/gui/value/$(am__dirstamp) \
	src/gui/value/$(DEPDIR)/$(am__dirstamp)
./src/gui/value/text.$(OBJEXT): src/gui/value/$(am__dirstamp) \
	src/gui/value/$(DEPDIR)/$(am__dirstamp)
./src/gui/value/image.$(OBJEXT): src/gui/value/$(am__dirstamp) \
	src/gui/value/$(DEPDIR)/$(am__dirstamp)
./src/gui/value/editor.$(OBJEXT): src/gui/value/$(am__dirstamp) \
	src/gui/value/$(DEPDIR)/$(am__dirstamp)
./src/gui/image_slice_window.$(OBJEXT): src/gui/$(am__dirstamp) \
	src/gui/$(DEPDIR)/$(am__dirstamp)
./src/gui/thumbnail_thread.$(OBJEXT): src/gui/$(am__dirstamp) \
	src/gui/$(DEPDIR)/$(am__dirstamp)
./src/gui/print_window.$(OBJEXT): src/gui/$(am__dirstamp) \
	src/gui/$(DEPDIR)/$(am__dirstamp)
./src/gui/about_window.$(OBJEXT): src/gui/$(am__dirstamp) \
	src/gui/$(DEPDIR)/$(am__dirstamp)
src/gui/symbol/$(am__dirstamp):
	@$(mkdir_p) ./src/gui/symbol
	@: > src/gui/symbol/$(am__dirstamp)
src/gui/symbol/$(DEPDIR)/$(am__dirstamp):
	@$(mkdir_p) ./src/gui/symbol/$(DEPDIR)
	@: > src/gui/symbol/$(DEPDIR)/$(am__dirstamp)
./src/gui/symbol/point_editor.$(OBJEXT):  \
	src/gui/symbol/$(am__dirstamp) \
	src/gui/symbol/$(DEPDIR)/$(am__dirstamp)
./src/gui/symbol/basic_shape_editor.$(OBJEXT):  \
	src/gui/symbol/$(am__dirstamp) \
	src/gui/symbol/$(DEPDIR)/$(am__dirstamp)
./src/gui/symbol/control.$(OBJEXT): src/gui/symbol/$(am__dirstamp) \
	src/gui/symbol/$(DEPDIR)/$(am__dirstamp)
./src/gui/symbol/select_editor.$(OBJEXT):  \
	src/gui/symbol/$(am__dirstamp) \
	src/gui/symbol/$(DEPDIR)/$(am__dirstamp)
./src/gui/symbol/editor.$(OBJEXT): src/gui/symbol/$(am__dirstamp) \
	src/gui/symbol/$(DEPDIR)/$(am__dirstamp)
./src/gui/symbol/part_list.$(OBJEXT): src/gui/symbol/$(am__dirstamp) \
	src/gui/symbol/$(DEPDIR)/$(am__dirstamp)
./src/gui/symbol/window.$(OBJEXT): src/gui/symbol/$(am__dirstamp) \
	src/gui/symbol/$(DEPDIR)/$(am__dirstamp)
./src/gui/update_checker.$(OBJEXT): src/gui/$(am__dirstamp) \
	src/gui/$(DEPDIR)/$(am__dirstamp)
./src/gui/new_window.$(OBJEXT): src/gui/$(am__dirstamp) \
	src/gui/$(DEPDIR)/$(am__dirstamp)
./src/gui/icon_menu.$(OBJEXT): src/gui/$(am__dirstamp) \
	src/gui/$(DEPDIR)/$(am__dirstamp)
./src/gui/util.$(OBJEXT): src/gui/$(am__dirstamp) \
	src/gui/$(DEPDIR)/$(am__dirstamp)
src/data/$(am__dirstamp):
	@$(mkdir_p) ./src/data
	@: > src/data/$(am__dirstamp)
src/data/$(DEPDIR)/$(am__dirstamp):
	@$(mkdir_p) ./src/data/$(DEPDIR)
	@: > src/data/$(DEPDIR)/$(am__dirstamp)
./src/data/field.$(OBJEXT): src/data/$(am__dirstamp) \
	src/data/$(DEPDIR)/$(am__dirstamp)
src/data/field/$(am__dirstamp):
	@$(mkdir_p) ./src/data/field
	@: > src/data/field/$(am__dirstamp)
src/data/field/$(DEPDIR)/$(am__dirstamp):
	@$(mkdir_p) ./src/data/field/$(DEPDIR)
	@: > src/data/field/$(DEPDIR)/$(am__dirstamp)
./src/data/field/color.$(OBJEXT): src/data/field/$(am__dirstamp) \
	src/data/field/$(DEPDIR)/$(am__dirstamp)
./src/data/field/symbol.$(OBJEXT): src/data/field/$(am__dirstamp) \
	src/data/field/$(DEPDIR)/$(am__dirstamp)
./src/data/field/multiple_choice.$(OBJEXT):  \
	src/data/field/$(am__dirstamp) \
	src/data/field/$(DEPDIR)/$(am__dirstamp)
./src/data/field/choice.$(OBJEXT): src/data/field/$(am__dirstamp) \
	src/data/field/$(DEPDIR)/$(am__dirstamp)
./src/data/field/boolean.$(OBJEXT): src/data/field/$(am__dirstamp) \
	src/data/field/$(DEPDIR)/$(am__dirstamp)
./src/data/field/text.$(OBJEXT): src/data/field/$(am__dirstamp) \
	src/data/field/$(DEPDIR)/$(am__dirstamp)
./src/data/field/image.$(OBJEXT): src/data/field/$(am__dirstamp) \
	src/data/field/$(DEPDIR)/$(am__dirstamp)
./src/data/symbol.$(OBJEXT): src/data/$(am__dirstamp) \
	src/data/$(DEPDIR)/$(am__dirstamp)
./src/data/stylesheet.$(OBJEXT): src/data/$(am__dirstamp) \
	src/data/$(DEPDIR)/$(am__dirstamp)
./src/data/set.$(OBJEXT): src/data/$(am__dirstamp) \
	src/data/$(DEPDIR)/$(am__dirstamp)
./src/data/font.$(OBJEXT): src/data/$(am__dirstamp) \
	src/data/$(DEPDIR)/$(am__dirstamp)
./src/data/locale.$(OBJEXT): src/data/$(am__dirstamp) \
	src/data/$(DEPDIR)/$(am__dirstamp)
./src/data/symbol_font.$(OBJEXT): src/data/$(am__dirstamp) \
	src/data/$(DEPDIR)/$(am__dirstamp)
src/data/action/$(am__dirstamp):
	@$(mkdir_p) ./src/data/action
	@: > src/data/action/$(am__dirstamp)
src/data/action/$(DEPDIR)/$(am__dirstamp):
	@$(mkdir_p) ./src/data/action/$(DEPDIR)
	@: > src/data/action/$(DEPDIR)/$(am__dirstamp)
./src/data/action/symbol.$(OBJEXT): src/data/action/$(am__dirstamp) \
	src/data/action/$(DEPDIR)/$(am__dirstamp)
./src/data/action/set.$(OBJEXT): src/data/action/$(am__dirstamp) \
	src/data/action/$(DEPDIR)/$(am__dirstamp)
./src/data/action/symbol_part.$(OBJEXT):  \
	src/data/action/$(am__dirstamp) \
	src/data/action/$(DEPDIR)/$(am__dirstamp)
./src/data/action/value.$(OBJEXT): src/data/action/$(am__dirstamp) \
	src/data/action/$(DEPDIR)/$(am__dirstamp)
./src/data/card.$(OBJEXT): src/data/$(am__dirstamp) \
	src/data/$(DEPDIR)/$(am__dirstamp)
src/data/format/$(am__dirstamp):
	@$(mkdir_p) ./src/data/format
	@: > src/data/format/$(am__dirstamp)
src/data/format/$(DEPDIR)/$(am__dirstamp):
	@$(mkdir_p) ./src/data/format/$(DEPDIR)
	@: > src/data/format/$(DEPDIR)/$(am__dirstamp)
./src/data/format/html.$(OBJEXT): src/data/format/$(am__dirstamp) \
	src/data/format/$(DEPDIR)/$(am__dirstamp)
./src/data/format/apprentice.$(OBJEXT):  \
	src/data/format/$(am__dirstamp) \
	src/data/format/$(DEPDIR)/$(am__dirstamp)
./src/data/format/mtg_editor.$(OBJEXT):  \
	src/data/format/$(am__dirstamp) \
	src/data/format/$(DEPDIR)/$(am__dirstamp)
./src/data/format/formats.$(OBJEXT): src/data/format/$(am__dirstamp) \
	src/data/format/$(DEPDIR)/$(am__dirstamp)
./src/data/format/image.$(OBJEXT): src/data/format/$(am__dirstamp) \
	src/data/format/$(DEPDIR)/$(am__dirstamp)
./src/data/format/mws.$(OBJEXT): src/data/format/$(am__dirstamp) \
	src/data/format/$(DEPDIR)/$(am__dirstamp)
./src/data/format/mse1.$(OBJEXT): src/data/format/$(am__dirstamp) \
	src/data/format/$(DEPDIR)/$(am__dirstamp)
./src/data/format/mse2.$(OBJEXT): src/data/format/$(am__dirstamp) \
	src/data/format/$(DEPDIR)/$(am__dirstamp)
./src/data/format/clipboard.$(OBJEXT):  \
	src/data/format/$(am__dirstamp) \
	src/data/format/$(DEPDIR)/$(am__dirstamp)
./src/data/statistics.$(OBJEXT): src/data/$(am__dirstamp) \
	src/data/$(DEPDIR)/$(am__dirstamp)
./src/data/settings.$(OBJEXT): src/data/$(am__dirstamp) \
	src/data/$(DEPDIR)/$(am__dirstamp)
./src/data/keyword.$(OBJEXT): src/data/$(am__dirstamp) \
	src/data/$(DEPDIR)/$(am__dirstamp)
./src/data/game.$(OBJEXT): src/data/$(am__dirstamp) \
	src/data/$(DEPDIR)/$(am__dirstamp)
src/util/io/$(am__dirstamp):
	@$(mkdir_p) ./src/util/io
	@: > src/util/io/$(am__dirstamp)
src/util/io/$(DEPDIR)/$(am__dirstamp):
	@$(mkdir_p) ./src/util/io/$(DEPDIR)
	@: > src/util/io/$(DEPDIR)/$(am__dirstamp)
./src/util/io/package.$(OBJEXT): src/util/io/$(am__dirstamp) \
	src/util/io/$(DEPDIR)/$(am__dirstamp)
./src/util/io/writer.$(OBJEXT): src/util/io/$(am__dirstamp) \
	src/util/io/$(DEPDIR)/$(am__dirstamp)
./src/util/io/get_member.$(OBJEXT): src/util/io/$(am__dirstamp) \
	src/util/io/$(DEPDIR)/$(am__dirstamp)
./src/util/io/reader.$(OBJEXT): src/util/io/$(am__dirstamp) \
	src/util/io/$(DEPDIR)/$(am__dirstamp)
./src/util/io/package_manager.$(OBJEXT): src/util/io/$(am__dirstamp) \
	src/util/io/$(DEPDIR)/$(am__dirstamp)
src/util/$(am__dirstamp):
	@$(mkdir_p) ./src/util
	@: > src/util/$(am__dirstamp)
src/util/$(DEPDIR)/$(am__dirstamp):
	@$(mkdir_p) ./src/util/$(DEPDIR)
	@: > src/util/$(DEPDIR)/$(am__dirstamp)
./src/util/rotation.$(OBJEXT): src/util/$(am__dirstamp) \
	src/util/$(DEPDIR)/$(am__dirstamp)
./src/util/action_stack.$(OBJEXT): src/util/$(am__dirstamp) \
	src/util/$(DEPDIR)/$(am__dirstamp)
./src/util/alignment.$(OBJEXT): src/util/$(am__dirstamp) \
	src/util/$(DEPDIR)/$(am__dirstamp)
./src/util/version.$(OBJEXT): src/util/$(am__dirstamp) \
	src/util/$(DEPDIR)/$(am__dirstamp)
./src/util/string.$(OBJEXT): src/util/$(am__dirstamp) \
	src/util/$(DEPDIR)/$(am__dirstamp)
./src/util/tagged_string.$(OBJEXT): src/util/$(am__dirstamp) \
	src/util/$(DEPDIR)/$(am__dirstamp)
./src/util/age.$(OBJEXT): src/util/$(am__dirstamp) \
	src/util/$(DEPDIR)/$(am__dirstamp)
./src/util/error.$(OBJEXT): src/util/$(am__dirstamp) \
	src/util/$(DEPDIR)/$(am__dirstamp)
src/$(am__dirstamp):
	@$(mkdir_p) ./src
	@: > src/$(am__dirstamp)
src/$(DEPDIR)/$(am__dirstamp):
	@$(mkdir_p) ./src/$(DEPDIR)
	@: > src/$(DEPDIR)/$(am__dirstamp)
./src/main.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
./src/code_template.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/render/card/$(am__dirstamp):
	@$(mkdir_p) ./src/render/card
	@: > src/render/card/$(am__dirstamp)
src/render/card/$(DEPDIR)/$(am__dirstamp):
	@$(mkdir_p) ./src/render/card/$(DEPDIR)
	@: > src/render/card/$(DEPDIR)/$(am__dirstamp)
./src/render/card/viewer.$(OBJEXT): src/render/card/$(am__dirstamp) \
	src/render/card/$(DEPDIR)/$(am__dirstamp)
src/render/text/$(am__dirstamp):
	@$(mkdir_p) ./src/render/text
	@: > src/render/text/$(am__dirstamp)
src/render/text/$(DEPDIR)/$(am__dirstamp):
	@$(mkdir_p) ./src/render/text/$(DEPDIR)
	@: > src/render/text/$(DEPDIR)/$(am__dirstamp)
./src/render/text/symbol.$(OBJEXT): src/render/text/$(am__dirstamp) \
	src/render/text/$(DEPDIR)/$(am__dirstamp)
./src/render/text/font.$(OBJEXT): src/render/text/$(am__dirstamp) \
	src/render/text/$(DEPDIR)/$(am__dirstamp)
./src/render/text/compound.$(OBJEXT): src/render/text/$(am__dirstamp) \
	src/render/text/$(DEPDIR)/$(am__dirstamp)
./src/render/text/viewer.$(OBJEXT): src/render/text/$(am__dirstamp) \
	src/render/text/$(DEPDIR)/$(am__dirstamp)
./src/render/text/element.$(OBJEXT): src/render/text/$(am__dirstamp) \
	src/render/text/$(DEPDIR)/$(am__dirstamp)
src/render/value/$(am__dirstamp):
	@$(mkdir_p) ./src/render/value
	@: > src/render/value/$(am__dirstamp)
src/render/value/$(DEPDIR)/$(am__dirstamp):
	@$(mkdir_p) ./src/render/value/$(DEPDIR)
	@: > src/render/value/$(DEPDIR)/$(am__dirstamp)
./src/render/value/color.$(OBJEXT): src/render/value/$(am__dirstamp) \
	src/render/value/$(DEPDIR)/$(am__dirstamp)
./src/render/value/symbol.$(OBJEXT): src/render/value/$(am__dirstamp) \
	src/render/value/$(DEPDIR)/$(am__dirstamp)
./src/render/value/multiple_choice.$(OBJEXT):  \
	src/render/value/$(am__dirstamp) \
	src/render/value/$(DEPDIR)/$(am__dirstamp)
./src/render/value/choice.$(OBJEXT): src/render/value/$(am__dirstamp) \
	src/render/value/$(DEPDIR)/$(am__dirstamp)
./src/render/value/text.$(OBJEXT): src/render/value/$(am__dirstamp) \
	src/render/value/$(DEPDIR)/$(am__dirstamp)
./src/render/value/image.$(OBJEXT): src/render/value/$(am__dirstamp) \
	src/render/value/$(DEPDIR)/$(am__dirstamp)
./src/render/value/viewer.$(OBJEXT): src/render/value/$(am__dirstamp) \
	src/render/value/$(DEPDIR)/$(am__dirstamp)
src/render/symbol/$(am__dirstamp):
	@$(mkdir_p) ./src/render/symbol
	@: > src/render/symbol/$(am__dirstamp)
src/render/symbol/$(DEPDIR)/$(am__dirstamp):
	@$(mkdir_p) ./src/render/symbol/$(DEPDIR)
	@: > src/render/symbol/$(DEPDIR)/$(am__dirstamp)
./src/render/symbol/filter.$(OBJEXT):  \
	src/render/symbol/$(am__dirstamp) \
	src/render/symbol/$(DEPDIR)/$(am__dirstamp)
./src/render/symbol/viewer.$(OBJEXT):  \
	src/render/symbol/$(am__dirstamp) \
	src/render/symbol/$(DEPDIR)/$(am__dirstamp)
src/script/$(am__dirstamp):
	@$(mkdir_p) ./src/script
	@: > src/script/$(am__dirstamp)
src/script/$(DEPDIR)/$(am__dirstamp):
	@$(mkdir_p) ./src/script/$(DEPDIR)
	@: > src/script/$(DEPDIR)/$(am__dirstamp)
./src/script/parser.$(OBJEXT): src/script/$(am__dirstamp) \
	src/script/$(DEPDIR)/$(am__dirstamp)
./src/script/functions.$(OBJEXT): src/script/$(am__dirstamp) \
	src/script/$(DEPDIR)/$(am__dirstamp)
./src/script/image.$(OBJEXT): src/script/$(am__dirstamp) \
	src/script/$(DEPDIR)/$(am__dirstamp)
./src/script/dependency.$(OBJEXT): src/script/$(am__dirstamp) \
	src/script/$(DEPDIR)/$(am__dirstamp)
./src/script/value.$(OBJEXT): src/script/$(am__dirstamp) \
	src/script/$(DEPDIR)/$(am__dirstamp)
./src/script/script.$(OBJEXT): src/script/$(am__dirstamp) \
	src/script/$(DEPDIR)/$(am__dirstamp)
./src/script/context.$(OBJEXT): src/script/$(am__dirstamp) \
	src/script/$(DEPDIR)/$(am__dirstamp)
./src/script/script_manager.$(OBJEXT): src/script/$(am__dirstamp) \
	src/script/$(DEPDIR)/$(am__dirstamp)
./src/script/scriptable.$(OBJEXT): src/script/$(am__dirstamp) \
	src/script/$(DEPDIR)/$(am__dirstamp)
magicseteditor$(EXEEXT): $(magicseteditor_OBJECTS) $(magicseteditor_DEPENDENCIES) 
	@rm -f magicseteditor$(EXEEXT)
	$(CXXLINK) $(magicseteditor_LDFLAGS) $(magicseteditor_OBJECTS) $(magicseteditor_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f ./src/code_template.$(OBJEXT)
	-rm -f ./src/data/action/set.$(OBJEXT)
	-rm -f ./src/data/action/symbol.$(OBJEXT)
	-rm -f ./src/data/action/symbol_part.$(OBJEXT)
	-rm -f ./src/data/action/value.$(OBJEXT)
	-rm -f ./src/data/card.$(OBJEXT)
	-rm -f ./src/data/field.$(OBJEXT)
	-rm -f ./src/data/field/boolean.$(OBJEXT)
	-rm -f ./src/data/field/choice.$(OBJEXT)
	-rm -f ./src/data/field/color.$(OBJEXT)
	-rm -f ./src/data/field/image.$(OBJEXT)
	-rm -f ./src/data/field/multiple_choice.$(OBJEXT)
	-rm -f ./src/data/field/symbol.$(OBJEXT)
	-rm -f ./src/data/field/text.$(OBJEXT)
	-rm -f ./src/data/font.$(OBJEXT)
	-rm -f ./src/data/format/apprentice.$(OBJEXT)
	-rm -f ./src/data/format/clipboard.$(OBJEXT)
	-rm -f ./src/data/format/formats.$(OBJEXT)
	-rm -f ./src/data/format/html.$(OBJEXT)
	-rm -f ./src/data/format/image.$(OBJEXT)
	-rm -f ./src/data/format/mse1.$(OBJEXT)
	-rm -f ./src/data/format/mse2.$(OBJEXT)
	-rm -f ./src/data/format/mtg_editor.$(OBJEXT)
	-rm -f ./src/data/format/mws.$(OBJEXT)
	-rm -f ./src/data/game.$(OBJEXT)
	-rm -f ./src/data/keyword.$(OBJEXT)
	-rm -f ./src/data/locale.$(OBJEXT)
	-rm -f ./src/data/set.$(OBJEXT)
	-rm -f ./src/data/settings.$(OBJEXT)
	-rm -f ./src/data/statistics.$(OBJEXT)
	-rm -f ./src/data/stylesheet.$(OBJEXT)
	-rm -f ./src/data/symbol.$(OBJEXT)
	-rm -f ./src/data/symbol_font.$(OBJEXT)
	-rm -f ./src/gfx/bezier.$(OBJEXT)
	-rm -f ./src/gfx/blend_image.$(OBJEXT)
	-rm -f ./src/gfx/color.$(OBJEXT)
	-rm -f ./src/gfx/combine_image.$(OBJEXT)
	-rm -f ./src/gfx/image_effects.$(OBJEXT)
	-rm -f ./src/gfx/mask_image.$(OBJEXT)
	-rm -f ./src/gfx/polynomial.$(OBJEXT)
	-rm -f ./src/gfx/resample_image.$(OBJEXT)
	-rm -f ./src/gfx/resample_text.$(OBJEXT)
	-rm -f ./src/gfx/rotate_image.$(OBJEXT)
	-rm -f ./src/gui/about_window.$(OBJEXT)
	-rm -f ./src/gui/card_select_window.$(OBJEXT)
	-rm -f ./src/gui/control/card_editor.$(OBJEXT)
	-rm -f ./src/gui/control/card_list.$(OBJEXT)
	-rm -f ./src/gui/control/card_list_column_select.$(OBJEXT)
	-rm -f ./src/gui/control/card_viewer.$(OBJEXT)
	-rm -f ./src/gui/control/filtered_card_list.$(OBJEXT)
	-rm -f ./src/gui/control/gallery_list.$(OBJEXT)
	-rm -f ./src/gui/control/graph.$(OBJEXT)
	-rm -f ./src/gui/control/image_card_list.$(OBJEXT)
	-rm -f ./src/gui/control/native_look_editor.$(OBJEXT)
	-rm -f ./src/gui/control/package_list.$(OBJEXT)
	-rm -f ./src/gui/control/select_card_list.$(OBJEXT)
	-rm -f ./src/gui/control/text_ctrl.$(OBJEXT)
	-rm -f ./src/gui/drop_down_list.$(OBJEXT)
	-rm -f ./src/gui/icon_menu.$(OBJEXT)
	-rm -f ./src/gui/image_slice_window.$(OBJEXT)
	-rm -f ./src/gui/new_window.$(OBJEXT)
	-rm -f ./src/gui/preferences_window.$(OBJEXT)
	-rm -f ./src/gui/print_window.$(OBJEXT)
	-rm -f ./src/gui/set/cards_panel.$(OBJEXT)
	-rm -f ./src/gui/set/keywords_panel.$(OBJEXT)
	-rm -f ./src/gui/set/panel.$(OBJEXT)
	-rm -f ./src/gui/set/set_info_panel.$(OBJEXT)
	-rm -f ./src/gui/set/stats_panel.$(OBJEXT)
	-rm -f ./src/gui/set/style_panel.$(OBJEXT)
	-rm -f ./src/gui/set/window.$(OBJEXT)
	-rm -f ./src/gui/symbol/basic_shape_editor.$(OBJEXT)
	-rm -f ./src/gui/symbol/control.$(OBJEXT)
	-rm -f ./src/gui/symbol/editor.$(OBJEXT)
	-rm -f ./src/gui/symbol/part_list.$(OBJEXT)
	-rm -f ./src/gui/symbol/point_editor.$(OBJEXT)
	-rm -f ./src/gui/symbol/select_editor.$(OBJEXT)
	-rm -f ./src/gui/symbol/window.$(OBJEXT)
	-rm -f ./src/gui/thumbnail_thread.$(OBJEXT)
	-rm -f ./src/gui/update_checker.$(OBJEXT)
	-rm -f ./src/gui/util.$(OBJEXT)
	-rm -f ./src/gui/value/choice.$(OBJEXT)
	-rm -f ./src/gui/value/color.$(OBJEXT)
	-rm -f ./src/gui/value/editor.$(OBJEXT)
	-rm -f ./src/gui/value/image.$(OBJEXT)
	-rm -f ./src/gui/value/multiple_choice.$(OBJEXT)
	-rm -f ./src/gui/value/symbol.$(OBJEXT)
	-rm -f ./src/gui/value/text.$(OBJEXT)
	-rm -f ./src/gui/welcome_window.$(OBJEXT)
	-rm -f ./src/main.$(OBJEXT)
	-rm -f ./src/render/card/viewer.$(OBJEXT)
	-rm -f ./src/render/symbol/filter.$(OBJEXT)
	-rm -f ./src/render/symbol/viewer.$(OBJEXT)
	-rm -f ./src/render/text/compound.$(OBJEXT)
	-rm -f ./src/render/text/element.$(OBJEXT)
	-rm -f ./src/render/text/font.$(OBJEXT)
	-rm -f ./src/render/text/symbol.$(OBJEXT)
	-rm -f ./src/render/text/viewer.$(OBJEXT)
	-rm -f ./src/render/value/choice.$(OBJEXT)
	-rm -f ./src/render/value/color.$(OBJEXT)
	-rm -f ./src/render/value/image.$(OBJEXT)
	-rm -f ./src/render/value/multiple_choice.$(OBJEXT)
	-rm -f ./src/render/value/symbol.$(OBJEXT)
	-rm -f ./src/render/value/text.$(OBJEXT)
	-rm -f ./src/render/value/viewer.$(OBJEXT)
	-rm -f ./src/script/context.$(OBJEXT)
	-rm -f ./src/script/dependency.$(OBJEXT)
	-rm -f ./src/script/functions.$(OBJEXT)
	-rm -f ./src/script/image.$(OBJEXT)
	-rm -f ./src/script/parser.$(OBJEXT)
	-rm -f ./src/script/script.$(OBJEXT)
	-rm -f ./src/script/script_manager.$(OBJEXT)
	-rm -f ./src/script/scriptable.$(OBJEXT)
	-rm -f ./src/script/value.$(OBJEXT)
	-rm -f ./src/util/action_stack.$(OBJEXT)
	-rm -f ./src/util/age.$(OBJEXT)
	-rm -f ./src/util/alignment.$(OBJEXT)
	-rm -f ./src/util/error.$(OBJEXT)
	-rm -f ./src/util/io/get_member.$(OBJEXT)
	-rm -f ./src/util/io/package.$(OBJEXT)
	-rm -f ./src/util/io/package_manager.$(OBJEXT)
	-rm -f ./src/util/io/reader.$(OBJEXT)
	-rm -f ./src/util/io/writer.$(OBJEXT)
	-rm -f ./src/util/rotation.$(OBJEXT)
	-rm -f ./src/util/string.$(OBJEXT)
	-rm -f ./src/util/tagged_string.$(OBJEXT)
	-rm -f ./src/util/version.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./src/$(DEPDIR)/code_template.Po
include ./src/$(DEPDIR)/main.Po
include ./src/data/$(DEPDIR)/card.Po
include ./src/data/$(DEPDIR)/field.Po
include ./src/data/$(DEPDIR)/font.Po
include ./src/data/$(DEPDIR)/game.Po
include ./src/data/$(DEPDIR)/keyword.Po
include ./src/data/$(DEPDIR)/locale.Po
include ./src/data/$(DEPDIR)/set.Po
include ./src/data/$(DEPDIR)/settings.Po
include ./src/data/$(DEPDIR)/statistics.Po
include ./src/data/$(DEPDIR)/stylesheet.Po
include ./src/data/$(DEPDIR)/symbol.Po
include ./src/data/$(DEPDIR)/symbol_font.Po
include ./src/data/action/$(DEPDIR)/set.Po
include ./src/data/action/$(DEPDIR)/symbol.Po
include ./src/data/action/$(DEPDIR)/symbol_part.Po
include ./src/data/action/$(DEPDIR)/value.Po
include ./src/data/field/$(DEPDIR)/boolean.Po
include ./src/data/field/$(DEPDIR)/choice.Po
include ./src/data/field/$(DEPDIR)/color.Po
include ./src/data/field/$(DEPDIR)/image.Po
include ./src/data/field/$(DEPDIR)/multiple_choice.Po
include ./src/data/field/$(DEPDIR)/symbol.Po
include ./src/data/field/$(DEPDIR)/text.Po
include ./src/data/format/$(DEPDIR)/apprentice.Po
include ./src/data/format/$(DEPDIR)/clipboard.Po
include ./src/data/format/$(DEPDIR)/formats.Po
include ./src/data/format/$(DEPDIR)/html.Po
include ./src/data/format/$(DEPDIR)/image.Po
include ./src/data/format/$(DEPDIR)/mse1.Po
include ./src/data/format/$(DEPDIR)/mse2.Po
include ./src/data/format/$(DEPDIR)/mtg_editor.Po
include ./src/data/format/$(DEPDIR)/mws.Po
include ./src/gfx/$(DEPDIR)/bezier.Po
include ./src/gfx/$(DEPDIR)/blend_image.Po
include ./src/gfx/$(DEPDIR)/color.Po
include ./src/gfx/$(DEPDIR)/combine_image.Po
include ./src/gfx/$(DEPDIR)/image_effects.Po
include ./src/gfx/$(DEPDIR)/mask_image.Po
include ./src/gfx/$(DEPDIR)/polynomial.Po
include ./src/gfx/$(DEPDIR)/resample_image.Po
include ./src/gfx/$(DEPDIR)/resample_text.Po
include ./src/gfx/$(DEPDIR)/rotate_image.Po
include ./src/gui/$(DEPDIR)/about_window.Po
include ./src/gui/$(DEPDIR)/card_select_window.Po
include ./src/gui/$(DEPDIR)/drop_down_list.Po
include ./src/gui/$(DEPDIR)/icon_menu.Po
include ./src/gui/$(DEPDIR)/image_slice_window.Po
include ./src/gui/$(DEPDIR)/new_window.Po
include ./src/gui/$(DEPDIR)/preferences_window.Po
include ./src/gui/$(DEPDIR)/print_window.Po
include ./src/gui/$(DEPDIR)/thumbnail_thread.Po
include ./src/gui/$(DEPDIR)/update_checker.Po
include ./src/gui/$(DEPDIR)/util.Po
include ./src/gui/$(DEPDIR)/welcome_window.Po
include ./src/gui/control/$(DEPDIR)/card_editor.Po
include ./src/gui/control/$(DEPDIR)/card_list.Po
include ./src/gui/control/$(DEPDIR)/card_list_column_select.Po
include ./src/gui/control/$(DEPDIR)/card_viewer.Po
include ./src/gui/control/$(DEPDIR)/filtered_card_list.Po
include ./src/gui/control/$(DEPDIR)/gallery_list.Po
include ./src/gui/control/$(DEPDIR)/graph.Po
include ./src/gui/control/$(DEPDIR)/image_card_list.Po
include ./src/gui/control/$(DEPDIR)/native_look_editor.Po
include ./src/gui/control/$(DEPDIR)/package_list.Po
include ./src/gui/control/$(DEPDIR)/select_card_list.Po
include ./src/gui/control/$(DEPDIR)/text_ctrl.Po
include ./src/gui/set/$(DEPDIR)/cards_panel.Po
include ./src/gui/set/$(DEPDIR)/keywords_panel.Po
include ./src/gui/set/$(DEPDIR)/panel.Po
include ./src/gui/set/$(DEPDIR)/set_info_panel.Po
include ./src/gui/set/$(DEPDIR)/stats_panel.Po
include ./src/gui/set/$(DEPDIR)/style_panel.Po
include ./src/gui/set/$(DEPDIR)/window.Po
include ./src/gui/symbol/$(DEPDIR)/basic_shape_editor.Po
include ./src/gui/symbol/$(DEPDIR)/control.Po
include ./src/gui/symbol/$(DEPDIR)/editor.Po
include ./src/gui/symbol/$(DEPDIR)/part_list.Po
include ./src/gui/symbol/$(DEPDIR)/point_editor.Po
include ./src/gui/symbol/$(DEPDIR)/select_editor.Po
include ./src/gui/symbol/$(DEPDIR)/window.Po
include ./src/gui/value/$(DEPDIR)/choice.Po
include ./src/gui/value/$(DEPDIR)/color.Po
include ./src/gui/value/$(DEPDIR)/editor.Po
include ./src/gui/value/$(DEPDIR)/image.Po
include ./src/gui/value/$(DEPDIR)/multiple_choice.Po
include ./src/gui/value/$(DEPDIR)/symbol.Po
include ./src/gui/value/$(DEPDIR)/text.Po
include ./src/render/card/$(DEPDIR)/viewer.Po
include ./src/render/symbol/$(DEPDIR)/filter.Po
include ./src/render/symbol/$(DEPDIR)/viewer.Po
include ./src/render/text/$(DEPDIR)/compound.Po
include ./src/render/text/$(DEPDIR)/element.Po
include ./src/render/text/$(DEPDIR)/font.Po
include ./src/render/text/$(DEPDIR)/symbol.Po
include ./src/render/text/$(DEPDIR)/viewer.Po
include ./src/render/value/$(DEPDIR)/choice.Po
include ./src/render/value/$(DEPDIR)/color.Po
include ./src/render/value/$(DEPDIR)/image.Po
include ./src/render/value/$(DEPDIR)/multiple_choice.Po
include ./src/render/value/$(DEPDIR)/symbol.Po
include ./src/render/value/$(DEPDIR)/text.Po
include ./src/render/value/$(DEPDIR)/viewer.Po
include ./src/script/$(DEPDIR)/context.Po
include ./src/script/$(DEPDIR)/dependency.Po
include ./src/script/$(DEPDIR)/functions.Po
include ./src/script/$(DEPDIR)/image.Po
include ./src/script/$(DEPDIR)/parser.Po
include ./src/script/$(DEPDIR)/script.Po
include ./src/script/$(DEPDIR)/script_manager.Po
include ./src/script/$(DEPDIR)/scriptable.Po
include ./src/script/$(DEPDIR)/value.Po
include ./src/util/$(DEPDIR)/action_stack.Po
include ./src/util/$(DEPDIR)/age.Po
include ./src/util/$(DEPDIR)/alignment.Po
include ./src/util/$(DEPDIR)/error.Po
include ./src/util/$(DEPDIR)/rotation.Po
include ./src/util/$(DEPDIR)/string.Po
include ./src/util/$(DEPDIR)/tagged_string.Po
include ./src/util/$(DEPDIR)/version.Po
include ./src/util/io/$(DEPDIR)/get_member.Po
include ./src/util/io/$(DEPDIR)/package.Po
include ./src/util/io/$(DEPDIR)/package_manager.Po
include ./src/util/io/$(DEPDIR)/reader.Po
include ./src/util/io/$(DEPDIR)/writer.Po

.cpp.o:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`; \
	if $(CXXCOMPILE) -MT $@ -MD -MP -MF "$$depbase.Tpo" -c -o $@ $<; \
	then mv -f "$$depbase.Tpo" "$$depbase.Po"; else rm -f "$$depbase.Tpo"; exit 1; fi
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`; \
	if $(CXXCOMPILE) -MT $@ -MD -MP -MF "$$depbase.Tpo" -c -o $@ `$(CYGPATH_W) '$<'`; \
	then mv -f "$$depbase.Tpo" "$$depbase.Po"; else rm -f "$$depbase.Tpo"; exit 1; fi
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`
uninstall-info-am:

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	    $$tags $$unique; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	mkdir $(distdir)
	$(mkdir_p) $(distdir)/src
	@srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's|.|.|g'`; \
	list='$(DISTFILES)'; for file in $$list; do \
	  case $$file in \
	    $(srcdir)/*) file=`echo "$$file" | sed "s|^$$srcdirstrip/||"`;; \
	    $(top_srcdir)/*) file=`echo "$$file" | sed "s|^$$topsrcdirstrip/|$(top_builddir)/|"`;; \
	  esac; \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    dir="/$$dir"; \
	    $(mkdir_p) "$(distdir)$$dir"; \
	  else \
	    dir=''; \
	  fi; \
	  if test -d $$d/$$file; then \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
	-find $(distdir) -type d ! -perm -777 -exec chmod a+rwx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(SHELL) $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r $(distdir)
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bunzip2 -c $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && cd $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e '1{h;s/./=/g;p;x;}' -e '$${p;x;}'
distuninstallcheck:
	@cd $(distuninstallcheck_dir) \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS)
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(mkdir_p) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-rm -f src/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/$(am__dirstamp)
	-rm -f src/data/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/data/$(am__dirstamp)
	-rm -f src/data/action/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/data/action/$(am__dirstamp)
	-rm -f src/data/field/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/data/field/$(am__dirstamp)
	-rm -f src/data/format/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/data/format/$(am__dirstamp)
	-rm -f src/gfx/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/gfx/$(am__dirstamp)
	-rm -f src/gui/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/gui/$(am__dirstamp)
	-rm -f src/gui/control/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/gui/control/$(am__dirstamp)
	-rm -f src/gui/set/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/gui/set/$(am__dirstamp)
	-rm -f src/gui/symbol/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/gui/symbol/$(am__dirstamp)
	-rm -f src/gui/value/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/gui/value/$(am__dirstamp)
	-rm -f src/render/card/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/render/card/$(am__dirstamp)
	-rm -f src/render/symbol/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/render/symbol/$(am__dirstamp)
	-rm -f src/render/text/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/render/text/$(am__dirstamp)
	-rm -f src/render/value/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/render/value/$(am__dirstamp)
	-rm -f src/script/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/script/$(am__dirstamp)
	-rm -f src/util/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/util/$(am__dirstamp)
	-rm -f src/util/io/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/util/io/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./src/$(DEPDIR) ./src/data/$(DEPDIR) ./src/data/action/$(DEPDIR) ./src/data/field/$(DEPDIR) ./src/data/format/$(DEPDIR) ./src/gfx/$(DEPDIR) ./src/gui/$(DEPDIR) ./src/gui/control/$(DEPDIR) ./src/gui/set/$(DEPDIR) ./src/gui/symbol/$(DEPDIR) ./src/gui/value/$(DEPDIR) ./src/render/card/$(DEPDIR) ./src/render/symbol/$(DEPDIR) ./src/render/text/$(DEPDIR) ./src/render/value/$(DEPDIR) ./src/script/$(DEPDIR) ./src/util/$(DEPDIR) ./src/util/io/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

info: info-am

info-am:

install-data-am:

install-exec-am: install-binPROGRAMS

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./src/$(DEPDIR) ./src/data/$(DEPDIR) ./src/data/action/$(DEPDIR) ./src/data/field/$(DEPDIR) ./src/data/format/$(DEPDIR) ./src/gfx/$(DEPDIR) ./src/gui/$(DEPDIR) ./src/gui/control/$(DEPDIR) ./src/gui/set/$(DEPDIR) ./src/gui/symbol/$(DEPDIR) ./src/gui/value/$(DEPDIR) ./src/render/card/$(DEPDIR) ./src/render/symbol/$(DEPDIR) ./src/render/text/$(DEPDIR) ./src/render/value/$(DEPDIR) ./src/script/$(DEPDIR) ./src/util/$(DEPDIR) ./src/util/io/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-info-am

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-generic ctags dist dist-all dist-bzip2 \
	dist-gzip dist-shar dist-tarZ dist-zip distcheck distclean \
	distclean-compile distclean-generic distclean-hdr \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-binPROGRAMS install-data install-data-am install-exec \
	install-exec-am install-info install-info-am install-man \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic pdf pdf-am ps ps-am \
	tags uninstall uninstall-am uninstall-binPROGRAMS \
	uninstall-info-am

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
